### ISSUE TITLE
Charts not private?

### ISSUE THREAD

**Issue by FrankHendrix** [PortaDial/Charts#2]
Why is Charts not private? All others are...

**Comment by StefanGies99** [comment]
The reason why this one is public is that it contains standard Kubernetes configuration which needs to be accessible via a public endpoint. Github offers free hosting when this configuration is in a public repository. Configurations like this need to be publicly available for usage in [Helm](https://helm.sh/). Helm can be used as package manager for storing configuration how to Kubernetes needs to setup apps. This configuration repo contains no secret information. The only thing it does is describe the way we want to setup our apps. 

In this configuration we describe the following i.e.
- How much resources do we want to use
- What kind of load balancer do we want to use
- Describe how do we want to interact between load balancer and our apps

In the repositories of our apps we parse the secret information we want to let Kubernetes make use of. This is in a way of using configuration files like we use in our [Python Backend API](https://github.com/PortaDial/ConnectAPI/blob/master/config/production.yml), the production.yml contains the **Secret** variables which can be parsed by the Kubernetes system. 

For more information about the usage of Helm see this [link](https://helm.sh/docs/glossary/). The glossary mentions the following: `A Helm package that contains information sufficient for installing a set of Kubernetes resources into a Kubernetes cluster.`

In the future we may want to change the way we want to setup our deployment process. The current process is maybe a little bit complex and not straightforward to everyone. Recently Hashicorp released a tool called Waypoint which can make our deployment/release process much simpler, see [link](https://www.waypointproject.io/). The reason why we do deployments in this way is that there were no better initial options.
